#!/bin/ash

mount -v proc /proc -t proc
mount -v sysfs /sys -t sysfs

/load_kernel_modules 2>/dev/null
mdev -s

mkdir /live
mount -t tmpfs none /live

mkdir /live/livemedia
cdmediadetected=false
for device in sr0 sr1; do #seek Slackware-Live on CD/DVD device
	echo
	if [ -r /sys/block/$device ] && [ "`cat /sys/block/$device/removable`" == "1" ] && mount /dev/$device /live/livemedia 2>/dev/null; then
		if [ -f /live/livemedia/boot/slackware-live.sfs ]; then
			cdmediadetected=true
			break
		else
			umount /live/livemedia
		fi
	fi
done

if ! $cdmediadetected; then #seek Slackware-Live on USB device
	echo "Waiting for USB device ..."
	usbmediadetected=false
	sleeptime=0
	while ! $usbmediadetected && [ "$sleeptime" != "10" ]; do #try each seconds, but don't wait USB more than 10 seconds
		sleep 1
		let sleeptime+=1
		mdev -s
		for partition in /sys/block/sd?/sd*; do
			device=`echo $partition | cut -f4 -d/`
			partition=`echo $partition | cut -f5 -d/`
			if [ "`cat /sys/block/$device/removable`" == "1" ] && mount /dev/$partition /live/livemedia 2>/dev/null; then
				if [ -f /live/livemedia/boot/slackware-live.sfs ]; then
					usbmediadetected=true
					break
				else
					umount /live/livemedia
				fi

			fi
		done
	done
fi

mkdir /live/system
mount -o loop -t squashfs /live/livemedia/boot/slackware-live.sfs /live/system

mkdir /live/changes

mkdir /live/union
mount --bind /live/system/lib /lib #FIXME: could not link unionfs statically
mkdir /tmp #fuse needs to create temporary dir
unionfs -o allow_other,suid,dev,use_ino -o cow,max_files=524288 /live/changes=RW:/live/system=RO /live/union
#umount /live/system/lib #FIXME

for rep in livemedia system changes union; do 
	mkdir -p /live/union/live/$rep
	mount --bind /live/$rep /live/union/live/$rep
done

if $cdmediadetected; then
	echo "/dev/$device" > /live/union/var/run/slackware-live-media
fi

cat /rc.S > /live/union/etc/rc.d/rc.S
cat /rc.6 > /live/union/etc/rc.d/rc.6

mkdir -p  /live/union/tmp
mkdir -p  /live/union/sys
mkdir -p  /live/union/proc
mkdir -p  /live/union/dev
mknod /live/union/dev/console c 5 1

umount /proc
umount /sys
exec switch_root /live/union /sbin/init
